name: CI Workflow

on:
  push:
    branches:
      - '*'  # Triggers on push to any branch
  pull_request:
    branches:
      - '*'  # Triggers on pull requests to any branch

jobs:
  build:
    runs-on: windows-latest  # Specify Windows as the OS for the job

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify your Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest mycalculator.py
