name: CI Workflow

on:
  push:
    branches:
      - '*'  # Triggers on push to any branch
  pull_request:
    branches:
      - '*'  # Triggers on pull requests to any branch

jobs:
  build:
    runs-on: ${{ matrix.os }}  # Use the matrix variable for the OS
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # List the OS you want to test on

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest mycalculator.py
